import React from 'react';

const Features = () => {
    return (
        <div>
            <h1>Header</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus illo labore voluptates accusantium officia explicabo exercitationem dolorem molestias nemo nisi temporibus blanditiis maxime in sit, est iste fuga eligendi quae, vitae qui eum quam. Adipisci similique magni sequi perspiciatis, ullam distinctio quibusdam in tenetur atque ad, nostrum dignissimos doloremque illum voluptates amet unde! Eius explicabo sit quod accusamus optio recusandae distinctio dignissimos velit aperiam qui! Asperiores, tempora officia saepe ad suscipit excepturi dolorum cupiditate voluptatum rem! Inventore tempora esse ea illum sint id dicta recusandae omnis. Nisi deserunt ipsa voluptatum accusantium. Ullam minus, aperiam doloremque saepe dolorem amet quasi laudantium illo dignissimos cum distinctio. Eligendi optio, enim dicta, sunt accusamus, earum mollitia velit labore doloribus vero error neque harum aut molestias ducimus temporibus provident vitae itaque praesentium quae sapiente. Aspernatur saepe eveniet labore, voluptatibus ad vero soluta at inventore, quae voluptas ex laudantium veritatis sequi dicta ipsum repellat aut officiis doloremque voluptatem cum beatae repudiandae? Beatae reprehenderit magni vel corporis deleniti omnis dolore fuga odit atque esse. Vero, illo ratione quis molestias magni recusandae similique eveniet minima adipisci dignissimos, perspiciatis quo. Praesentium, quidem fuga, ducimus eligendi quae, suscipit cupiditate qui iure magnam inventore unde voluptatem blanditiis facere debitis dolores aut?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Distinctio fugiat sunt corrupti aliquid aliquam consequatur iusto asperiores delectus recusandae cum vero, exercitationem aspernatur excepturi id eaque, autem officia ex nihil animi voluptatibus quo! Maxime, corporis laboriosam culpa quae iste nobis ducimus temporibus dolor placeat hic excepturi, exercitationem fugiat perspiciatis alias! Eum rerum nemo expedita laudantium, soluta natus corporis molestiae? Aperiam architecto possimus dolores quaerat repellat facilis, voluptatibus fugit molestias culpa laborum amet autem laudantium earum maxime unde expedita? Perspiciatis dicta a possimus, nesciunt minus voluptatum perferendis magni quod, accusantium vel officia nihil pariatur error molestias impedit nobis officiis aperiam fuga architecto reprehenderit. Officiis voluptatum inventore ducimus similique, hic magni suscipit facere nihil! Quasi assumenda voluptatum magni, doloribus animi et minima commodi exercitationem cum vel distinctio ex. Asperiores tenetur hic perspiciatis esse molestias debitis sed consectetur amet commodi, quisquam cumque molestiae dolores maxime repellendus adipisci maiores magni vel optio accusamus suscipit pariatur, ratione non voluptatum. Illo voluptatum unde praesentium maiores labore excepturi, expedita optio aut sit, ducimus eum doloribus facilis vero? Autem, itaque fugit alias aliquid quod blanditiis repellat incidunt nemo nesciunt consequatur esse repellendus nam animi minima dolore atque neque deleniti dolorum porro. Eligendi accusantium nobis molestias, sint libero ex?</p>
        </div>
    );
}

export default Features;